### ISSUE TITLE
Softlock when fleeing

### ISSUE THREAD

**Issue by Agent517** [Idunno1/magical-glass#21]
For whatever reason, the game will occasionally get stuck in the FLEEFAIL state. I have absolutely no clue what's going on with this one, because most of the time fleeing just works correctly.

![image](https://github.com/Idunno1/magical-glass/assets/87152256/3070b97c-5631-4fc0-9a75-e84f5b9437fe)

**Comment by Idunno1** [comment]
i believe this got fixed
