### ISSUE TITLE
Library is not fully unloaded when switching to another mod

### ISSUE THREAD

**Issue by Agent517** [Idunno1/magical-glass#38]
If I start a mod that doesn't have magical glass installed and check if, say, LightBattle exists, it obviously doesn't. But if I load a mod with magical glass first and *then* go to the one without it, it does, even though it probably shouldn't.

https://github.com/Idunno1/magical-glass/assets/87152256/153b9702-342c-472e-9772-1b8afe9f3b46

Potential fix: add an `unload` function to the lib.lua file that sets the libRequired files to nil

**Comment by FireRainV** [comment]
Fixed it, your method worked:
https://github.com/Idunno1/magical-glass/pull/35/commits/0e2981cc672d96afe073659c17eafe2bc5bb4937

You can close this issue. Once my PR will be committed, it will be actually fixed.
