### ISSUE TITLE
this

### ISSUE THREAD

**Issue by Idunno1** [Idunno1/magical-glass#42]
<img width="604" alt="Screenshot 2023-12-08 011313" src="https://github.com/Idunno1/magical-glass/assets/8219159/0418812a-dff1-4312-bf9b-7be3f5071ffd">

**Comment by FireRainV** [comment]
![image](https://github.com/Idunno1/magical-glass/assets/19861141/ee522373-3d94-4bd5-877f-cbd562979e55)
Can't replicate

**Comment by FireRainV** [comment]
I see the issue, I will try to fix it.

**Comment by FireRainV** [comment]
fixed
