### ISSUE TITLE
Thorn Ring effect in light world

### ISSUE THREAD

**Issue by MikeGames573** [Idunno1/magical-glass#55]
https://github.com/Idunno1/magical-glass/assets/102537206/8795376d-5f4f-4ac7-9016-e3f3c54b9bf1

The thorn ring effects stay in the light world, i don't know if it is intended or not, so here am i reporting it.

**Comment by MikeGames573** [comment]
And now when i check stat, it gives this error:
mods/magical-glass-main/libraries/magical-glass/lib.lua:2496: attempt to call method 'getEquipDisplayName' (a nil value)

stack traceback:
	[C]: in function 'pcall'
	main.lua:400: in function 'getEquipDisplayName'
	mods/magical-glass-main/libraries/magical-glass/lib.lua:2496: in function 'draw'
	src/engine/object.lua:1647: in function 'drawSelf'
	src/engine/object.lua:1679: in function 'fullDraw'
	src/engine/object.lua:1631: in function 'drawChildren'
	src/engine/object.lua:301: in function 'draw'
	mods/magical-glass-main/libraries/magical-glass/lib.lua:2273: in function 'draw'
	src/engine/object.lua:1647: in function 'drawSelf'
	src/engine/object.lua:1679: in function 'fullDraw'
	...
	src/engine/object.lua:1679: in function 'fullDraw'
	src/engine/objects/stage.lua:93: in function 'draw'
	src/engine/game/game.lua:838: in function 'orig'
	src/kristal.lua:143: in function 'draw'
	main.lua:327: in function 'doDraw'
	main.lua:363: in function <main.lua:333>
	[C]: in function 'xpcall'
	main.lua:397: in function <main.lua:381>
	[C]: in function 'xpcall'
	[love "boot.lua"]:377: in function <[love "boot.lua"]:344>

Kristal v0.9.0-dev
Mod: magical-glass v1.1.1
Libraries:
magical-glass v1.1.1-dev

**Comment by FireRainV** [comment]
You're using an old version. Use the latest commit.

**Comment by MikeGames573** [comment]
> You're using an old version. Use the latest commit.

I downloaded the newest version, but it's still the same thing

**Comment by MikeGames573** [comment]
> And now when i check stat, it gives this error: mods/magical-glass-main/libraries/magical-glass/lib.lua:2496: attempt to call method 'getEquipDisplayName' (a nil value)
> 
> stack traceback: [C]: in function 'pcall' main.lua:400: in function 'getEquipDisplayName' mods/magical-glass-main/libraries/magical-glass/lib.lua:2496: in function 'draw' src/engine/object.lua:1647: in function 'drawSelf' src/engine/object.lua:1679: in function 'fullDraw' src/engine/object.lua:1631: in function 'drawChildren' src/engine/object.lua:301: in function 'draw' mods/magical-glass-main/libraries/magical-glass/lib.lua:2273: in function 'draw' src/engine/object.lua:1647: in function 'drawSelf' src/engine/object.lua:1679: in function 'fullDraw' ... src/engine/object.lua:1679: in function 'fullDraw' src/engine/objects/stage.lua:93: in function 'draw' src/engine/game/game.lua:838: in function 'orig' src/kristal.lua:143: in function 'draw' main.lua:327: in function 'doDraw' main.lua:363: in function main.lua:333 [C]: in function 'xpcall' main.lua:397: in function main.lua:381 [C]: in function 'xpcall' [love "boot.lua"]:377: in function <[love "boot.lua"]:344>
> 
> Kristal v0.9.0-dev Mod: magical-glass v1.1.1 Libraries: magical-glass v1.1.1-dev

And this error persist even with other equipped rings in dark world

**Comment by FireRainV** [comment]
create a new save, then try again

**Comment by MikeGames573** [comment]
I think it has something to do with light battles in dark world

**Comment by FireRainV** [comment]
of course it has to do with it, that part of the code is so spaghetti (not sure if @Idunno1 still needs it) that it won't use the correct inventory
